<?php
$width_table=900;
$width_global_table=930;
$withmenuleft=150;
$width_menugor=($width_table-$withmenuleft)/5;
$host="localhost";
$userbd="root";
$passwordbd="";
$databasename="edbomond_energotechnol";
?>